---
version: "2.1"
services:
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /opt/DockerApps/overseerr/config:/config
    ports:
      - 5055:5055
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.scope=monitorscope"