version: "3.7"

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
      - "2019:2019"
    volumes:
      - /opt/DockerApps/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /opt/DockerApps/caddy/site:/srv
      - caddy_data:/data
      - caddy_config:/config
    labels:
      - "com.centurylinklabs.watchtower.scope=monitorscope"

volumes:
  caddy_data:
  caddy_config: