---
version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /opt/DockerApps/sonarr/config:/config
      - /media/pi/Downloads/torrents:/downloads
      - /media/pi/Thorin:/Thorin
      - /media/pi/Balin:/Balin
      - /media/pi/Dori:/Dori
      - /media/pi/Nori:/Nori
    ports:
      - 8989:8989
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.scope=monitorscope" 