---
version: "3"
services:
  autoheal:
    image: willfarrell/autoheal
    container_name: autoheal
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      - AUTOHEAL_CONTAINER_LABEL=autoheal
      - AUTOHEAL_INTERVAL=10
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.scope=monitorscope" 