---
version: '3.3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    environment:
      - TZ=Asia/Kolkata
    volumes:
      - /opt/DockerApps/uptime-kuma/uptime-kuma-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3001:3001
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.scope=monitorscope" 