

services:
  rathole:
    image: rapiz1/rathole
    container_name: rathole-server
    ports:
      - "2333:2333"
      - "80:8080"
      - "443:8443"
      - "443:8443/udp"
      - "21115:21115"
      - "21116:21116"
      - "21116:21116/udp"
      - "21117:21117"
      - "21118:21118"
      - "21119:21119"
      - "56655:56655"
      - "56655:56655/udp"
      - "32400:32400"
      - "11434:11434"
    volumes:
      - /opt/DockerApps/rathole/server.toml:/app/config.toml
    command: --server /app/config.toml
    environment:
      - TZ=Asia/Kolkata
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.scope=monitorscope"
